// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0Vjh_256HRoSPav2kjwEbq2R9JDx08Y',
    appId: '1:1086460964157:web:b8cf8f7488c21e82ce6954',
    messagingSenderId: '1086460964157',
    projectId: 'rivo-c99c2',
    authDomain: 'rivo-c99c2.firebaseapp.com',
    storageBucket: 'rivo-c99c2.firebasestorage.app',
    measurementId: 'G-X0V4EE9S7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2j14r4PgrwiFf0mZlHF2mHhsE__sf0Y',
    appId: '1:1086460964157:android:4c086e6674c07d6ece6954',
    messagingSenderId: '1086460964157',
    projectId: 'rivo-c99c2',
    storageBucket: 'rivo-c99c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_k7y1KW_KB8iXWWP2Km254hTedGgfXs4',
    appId: '1:1086460964157:ios:e06693d87b2a4199ce6954',
    messagingSenderId: '1086460964157',
    projectId: 'rivo-c99c2',
    storageBucket: 'rivo-c99c2.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
